# Generated by Django 5.1.3 on 2024-11-15 19:50

from django.db import migrations


def add_roles(apps, schema_editor):
    Role = apps.get_model('tutoring', 'Role')
    roles = ['Student', 'Tutor', 'Parent']
    for role in roles:
        Role.objects.create(name=role)

class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_roles),
    ]