# Generated by Django 5.1.3 on 2024-11-10 21:49

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('tutoring', 'Role')
    Role.objects.create(name='Student')
    Role.objects.create(name='Tutor')
    Role.objects.create(name='Parent')

class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
