# Generated by Django 5.1.3 on 2024-11-21 19:25

from django.db import migrations

def create_popular_subjects(apps, schema_editor):
    Subject = apps.get_model('tutoring', 'Subject')
    popular_subjects = [
        'Mathematics',
        'English',
        'Science',
        'History',
        'Geography',
        'Physics',
        'Chemistry',
        'Biology',
        'Computer Science',
        'Physical Education'
    ]
    for subject in popular_subjects:
        Subject.objects.create(name=subject)

class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_auto_20241121_1924'),
    ]

    operations = [
        migrations.RunPython(create_popular_subjects),
    ]