# Generated by Django 5.1.3 on 2024-11-11 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_create_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='google_meet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='available_hours',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='available_hours',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='tutoring.availablehour'),
        ),
    ]
