# Generated by Django 5.1.3 on 2024-11-15 19:51

from django.db import migrations


# Generated by Django 5.1.3 on 2024-11-15 20:00

from django.db import migrations

def add_popular_subjects(apps, schema_editor):
    Subject = apps.get_model('tutoring', 'Subject')
    subjects = [
        'Mathematics',
        'English',
        'Science',
        'History',
        'Geography',
        'Physics',
        'Chemistry',
        'Biology'
    ]
    for subject in subjects:
        Subject.objects.create(name=subject)

class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_add_roles'),
    ]

    operations = [
        migrations.RunPython(add_popular_subjects),
    ]