# Generated by Django 5.1.3 on 2024-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_auto_20241121_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='isRemote',
            field=models.BooleanField(default=False, help_text='Is tutor willing to work remotely'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
