# Generated by Django 5.1.3 on 2024-11-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_create_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='goal',
            field=models.TextField(blank=True, help_text='What student wants to achieve', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tasks_description',
            field=models.TextField(blank=True, help_text='Description of tasks that student needs help with', null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='working_experience',
            field=models.ManyToManyField(blank=True, null=True, related_name='tutors', to='tutoring.workingexperience'),
        ),
    ]
