# Generated by Django 5.1.3 on 2024-11-14 14:03

from django.db import migrations

def create_education_levels(apps, schema_editor):
    EducationLevel = apps.get_model('tutoring', 'EducationLevel')
    levels = [
        ('primary', 'Primary School'),
        ('secondary', 'Secondary School'),
        ('university', 'University'),
    ]
    for level, display in levels:
        EducationLevel.objects.create(level=level)

class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_workingexperience_studentprofile_goal_and_more'),
    ]

    operations = [
        migrations.RunPython(create_education_levels),
    ]