# Generated by Django 5.1.3 on 2024-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_rename_isremote_tutorprofile_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
