# Generated by Django 5.1.3 on 2024-11-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_create_education_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('university', 'University')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='available_hours',
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='working_experience',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutoring.workingexperience'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='available_hours',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutoring.availablehour'),
        ),
    ]
