# Generated by Django 5.1.3 on 2024-11-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_lesson_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
