# Generated by Django 5.1.3 on 2024-11-24 10:59

from django.db import migrations, models

def create_education_levels(apps, schema_editor):
    EducationLevel = apps.get_model('tutoring', 'EducationLevel')
    EducationLevel.objects.bulk_create([
        EducationLevel(level='primary'),
        EducationLevel(level='secondary'),
        EducationLevel(level='university'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_lesson_is_remote'),
    ]

    operations = [
        migrations.RunPython(create_education_levels),
    ]

