# Generated by Django 5.1.3 on 2024-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_create_education_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='accepted_by',
            field=models.CharField(blank=True, choices=[('Tutor', 'Tutor'), ('Student', 'Student'), ('Parent', 'Parent')], max_length=7, null=True),
        ),
    ]
