# Generated by Django 5.1.3 on 2024-11-30 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_googlecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
