# Generated by Django 5.1.3 on 2024-11-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_googlecredentials_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='refresh_token',
        ),
    ]
