# Generated by Django 5.1.3 on 2024-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0014_remove_googlecredentials_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
