# Generated by Django 5.1.3 on 2024-11-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0015_googlecredentials_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='lesson_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_for_lessons', to='tutoring.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'document')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='tutoring.lessondocument'),
        ),
    ]
