# Generated by Django 5.1.3 on 2024-12-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0016_lessondocument_lesson_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonpayment',
            name='payment',
        ),
        migrations.AddField(
            model_name='lessonpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lessonpayment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
